<?php

function lcpmx_footer_menu() {
    $items['aviso-privacidad'] = array(
        'title' => 'Aviso de privacidad',
        'description' => 'Aviso de privacidad.',
        'page callback' => 'aviso_privacidad',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => TRUE,
        'access arguments' => array('access content')
    );

    $items['directorio'] = array(
        'title' => 'Directorio',
        'description' => 'Directorio.',
        'page callback' => 'directorio',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => TRUE,
        'access arguments' => array('access content')
    );
    return $items;
}
function lcpmx_footer_help($path, $arg) {
    if ($path == 'admin/help#lcpmx_footer') {
        return t('Muestra el footer en todo el sitio');
    }
}

function lcpmx_footer_block_info() {
    $blocks['lcpmx_footer'] = array(
        'info' => t('LaCapitalMX Footer')
    );

    $blocks['lcpmx_aviso_privacidad'] = array(
        'info' => t('LaCapitalMX Aviso Privacidad')
    );

    $blocks['lcpmx_directorio'] = array(
        'info' => t('LaCapitalMX Directorio')
    );
    return $blocks;
}

function lcpmx_footer_block_view($delta = '') {
    $block = array(
        'subject' => t(''),
        'content' => '',
    );

    if ($delta == 'lcpmx_footer') {
        $block['content'] = array(
            '#theme' => 'lcpmx_footer'
        );
    };

    if ($delta == 'lcpmx_aviso_privacidad') {
        $block['content'] = array(
            '#theme' => 'lcpmx_aviso_privacidad'
        );
    };

    if ($delta == 'lcpmx_directorio') {
        $block['content'] = array(
            '#theme' => 'lcpmx_directorio'
        );
    };
    return $block;
}

function lcpmx_footer_theme($existing, $type, $theme, $path) {
    return array(
        'lcpmx_footer' => array(
            'variables' => array(
                'items_lcpmx_footer' => NULL,
            ),
            'template' => 'lcpmx_footer',
        ),
        'lcpmx_aviso_privacidad' => array(
            'variables' => array(
                'items_aviso_privacidad' => NULL,
            ),
            'template' => 'lcpmx_aviso_privacidad',
        ),
        'lcpmx_directorio' => array(
            'variables' => array(
                'items_lcpmx_directorio' => NULL,
            ),
            'template' => 'lcpmx_directorio',
        ),
    );
}

function template_preprocess_lcpmx_footer(&$variables) {
    $variables['items_lcpmx_footer'] = array(
        'Directorio' => 'directorio',
        'Publicidad' => 'contact',
        //'Suscripciones' => 'suscripciones',
        'Aviso de privacidad' => 'aviso-privacidad',
        'Contacto' => 'contact',
    );
}

function aviso_privacidad(){
    return "";
}
function directorio(){
    return "";
}

/**
 * Implements hook_form_alter().
 */
function lcpmx_footer_form_alter(&$form, $form_state, $form_id) {
    switch ($form_id) {
        case 'contact_site_form':

            $form['tel'] = array(
                '#title' => t('Teléfono'),
                '#type' => 'textfield',
                '#required' => TRUE,
            );

            $form['name'] = array(
                '#title' => t('Nombre'),
                '#type' => 'textfield',
                '#required' => TRUE,
            );

            $form['mail']["#title"]= t('Correo Electrónico');
            $form['mail']["#default_value'"]= "";
            $form['mail']["#value'"]= "";

            $order = array(
                '1' => 'name',
                '2' => 'mail',
                '3' => 'tel',
                '4' => 'subject',
                '5' => 'message',
                '6' => 'copy',
            );

            drupal_add_css(drupal_get_path('module', 'lcpmx_footer') . '/contact.css');


            foreach ($order as $key => $field) {
                $form[$field]['#weight'] = $key;
            }

            break;
    }
    $dateformat = 'Y-m-d H:i';
    $form['field_fecha_nacimiento']["#after_build"]=array("lcpmx_format_year");
    $form['field_delegacion']["#after_build"]=array("lcpmx_delegaciones");


    //print_r($form['field_fecha_nacimiento']);

}

function lcpmx_format_year($form_element, &$form_state){
    // We unset the current values

    unset($form_element["und"][0]["value"]["year"]["#options"]);

    // Now we set the range we want
    $max_age = date('Y') - 60; // 100 years ago
    $min_age = date('Y')-18; // 7 years ago

    // Now we populate the array
    $form_element["und"][0]["value"]["year"]["#options"] = array();
    foreach (range($max_age, $min_age) as $year){
        $form_element["und"][0]["value"]["year"]["#options"][$year] = $year;
    }

    // We return our modified element
    return $form_element;
}

function lcpmx_delegaciones($form_element, &$form_state){
    // We unset the current values

    unset(
        $form_element["und"]["#options"][309292],
        $form_element["und"]["#options"][309294],
        $form_element["und"]["#options"][309290],
        $form_element["und"]["#options"][309298],
        $form_element["und"]["#options"][309295],
        $form_element["und"]["#options"][309300],
        $form_element["und"]["#options"][309298],
        $form_element["und"]["#options"][309296]
    );

    return $form_element;
}

function getRevista(){
    $revista=false;
    $query=db_select('node', 'n');
    $query->fields('n', array('nid'));
    $query->condition('n.type', "revista", '=');
    $query->condition('n.status', 1, '=');

    $query->orderBy('n.created', 'DESC');
    $query->range(0, 1);
    $result = $query->execute()->fetchAll();

    if($result){
        $node=node_load($result[0]->nid);

        $revista= array(
            'nid' => $node->nid,
            'url'=>url("node/".$node->nid),
            'title' => $node->title,
            //'portada' => image_style_url($style,($image['uri'])? $image["uri"] : ""),
            'portada' => file_create_url($node->field_image['und'][0]['uri']),
            'file'=>file_create_url($node->field_revista['und'][0]['uri']),
        );
        return $revista;
    }
}

function getSuperBanner(){
    $revista=false;
    $query=db_select('node', 'n');
    $query->fields('n', array('nid'));
    $query->condition('n.type', "super_banner", '=');
    $query->condition('n.status', 1, '=');

    $query->orderBy('n.created', 'DESC');
    $query->range(0, 1);
    $result = $query->execute()->fetchAll();

    if($result){
        $node=node_load($result[0]->nid);

        $banner= array(
            'image' => file_create_url($node->field_image['und'][0]['uri']),
            'target'=>file_create_url($node->field_target['und'][0]['value']),
        );
        return $banner;
    }
}