language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - sudo beanstalkd -d -l 127.0.0.1 -p 11300

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - phpunit --configuration phpunit.xml.dist

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
